### ISSUE TITLE
Create project structure for the Python project

### ISSUE THREAD

**Issue by chenzhao299** [UBC-MDS/noaastn#3]
- [x] We have created the project structure for this python project and pushed it as a public repository in the UBC-MDS organization on Github.com

- [x] The contributors' names are shared in the Contributors section of README.md file

- [x] Need to review 'CONDUCT' and 'CONTRIBUTING' file to make sure it adapts with appropriate attributions

- [x] Need to finish 'README.md' file

**Comment by spentelow** [comment]
Breakdown of readme requirements/tasks:

- [x] a summary paragraph that describes the project at a high level
- a bulleted list of the functions (and datasets if applicable) that will be included in the package (this should be a 1-2 sentence description for each function/dataset)
  - [x] get_stations_info
  - [x] get_weather_data
  - [x] plot_weather_data
- [x] a paragraph describing where your packages fit into the Python ecosystem (are there any other Python packages that have the same/similar functionality? Provide links to any that do. If none exist, then clearly state this as well).
