### ISSUE TITLE
Initiate package review

### ISSUE THREAD

**Issue by spentelow** [UBC-MDS/noaastn#42]
Each team must initiate a review request by opening an issue per package in the [UBC-MDS/software-review-2021 repository](https://github.com/UBC-MDS/software-review-2021).
- For initiating a reviewing request in Python, use the template under Submit Software for Review at [this link](https://github.com/pyOpenSci/software-review/issues/new/choose).

**Comment by chenzhao299** [comment]
Hi guys, our review requests are setup here:
https://github.com/UBC-MDS/software-review-2021/issues/28
https://github.com/UBC-MDS/software-review-2021/issues/29

There are several questions I would like to hear your options about：
- Does our packages falls into the right categories I selected in the "Scope" section? (I'm not too sure about the category "reproducibility" for python package and "workflow automation" in R package. But I think our packages are not created for those purpose, so we should not be included in that category
- I didn't selected any in "Publication options" section. Do we need to select it?
- If there are any update in the future in the DESCRIPTION file before our submission, please let me know. I need to update the "DESCRIPTION" section for the R package. 

Thank you!

**Comment by chenzhao299** [comment]
Updated the review request for python package with the lastest release number
