### ISSUE TITLE
Manage issues

### ISSUE THREAD

**Issue by chenzhao299** [UBC-MDS/noaastn#7]
- Remember to assign each issue of each function to a single person on the team after add every team member as contributor to this project
- Create project boards and milestones

**Comment by spentelow** [comment]
Adding text from milestone requirements for reference.

**Manage issues**

_rubric={mechanics:10}_

Manage issues effectively through project boards and milestones, make it clear who is responsible for what and what project milestone each task is associated with. In particular, create an issue for each function in the package. Each of these issues must be assigned to a single person on the team. We want all of you to get coding experience in the project and each team member should be responsible for a function in R and Python. So if you are a team of four, you'll be writing four functions for each package and if you are a team of three, you will be writing three functions for each package.

**Comment by chenzhao299** [comment]
Follows exactly the workflow as instructed during the process. Ready for release
